import { UserRole, Permission } from '@/types/auth';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  'Super Admin': [
    'buyers.read',
    'buyers.write',
    'orders.read',
    'orders.write',
    'production.read',
    'production.write',
    'production.publish',
    'documents.read',
    'documents.write',
    'documents.delete',
    'samples.read',
    'samples.write',
    'samples.approve',
    'quality.read',
    'quality.write',
    'shipments.read',
    'shipments.write',
    'users.read',
    'users.write',
    'settings.read',
    'settings.write',
    'auditLogs.read',
  ],
  'Admin': [
    'buyers.read',
    'buyers.write',
    'orders.read',
    'orders.write',
    'production.read',
    'production.write',
    'production.publish',
    'documents.read',
    'documents.write',
    'documents.delete',
    'samples.read',
    'samples.write',
    'samples.approve',
    'quality.read',
    'quality.write',
    'shipments.read',
    'shipments.write',
    'users.read',
    'users.write',
    'settings.read',
    'auditLogs.read',
  ],
  'Operations Manager': [
    'buyers.read',
    'buyers.write',
    'orders.read',
    'orders.write',
    'production.read',
    'production.write',
    'production.publish',
    'documents.read',
    'documents.write',
    'samples.read',
    'samples.write',
    'quality.read',
    'quality.write',
    'shipments.read',
    'shipments.write',
  ],
  'Merchandiser': [
    'buyers.read',
    'orders.read',
    'orders.write',
    'production.read',
    'production.write',
    'production.publish',
    'documents.read',
    'documents.write',
    'samples.read',
    'samples.write',
    'quality.read',
    'shipments.read',
    'shipments.write',
  ],
  'Production Staff': [
    'orders.read',
    'production.read',
    'production.write',
    'documents.read',
  ],
  'QC Staff': [
    'orders.read',
    'quality.read',
    'quality.write',
    'documents.read',
    'documents.write',
  ],
  'Buyer': [
    'orders.read',
    'production.read',
    'documents.read',
    'samples.read',
    'samples.approve',
    'quality.read',
    'shipments.read',
  ],
};

export function hasPermission(role: UserRole | undefined, permission: Permission): boolean {
  if (!role) return false;
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
}
